backend:
  name: git-gateway
  branch: main

media_folder: "public/images/portfolio"
public_folder: "/images/portfolio"

collections:
  - name: "portfolio"
    label: "Portfolio Items"
    folder: "src/data/portfolio-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Corporate", "Events", "Brand", "Weddings", "Studio Portraits"]}
      - {label: "Image", name: "imageUrl", widget: "image"}